/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StartRouteImport } from './routes/start'
import { Route as TopupRouteImport } from './routes/topup'
import { Route as ApiForgotRouteImport } from './routes/api/forgot'
import { Route as ApiLoginRouteImport } from './routes/api/login'
import { Route as ApiLogoutRouteImport } from './routes/api/logout'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as ApiResetRouteImport } from './routes/api/reset'
import { Route as ApiSignupRouteImport } from './routes/api/signup'
import { Route as LearnIndexRouteImport } from './routes/learn/index'
import { Route as LearnSlugRouteImport } from './routes/learn/$slug'
import { Route as LearnGlossaryRouteImport } from './routes/learn/glossary'
import { Route as LearnQuizRouteImport } from './routes/learn/quiz'
import { Route as SitesIdRouteImport } from './routes/sites/$id'
import { Route as ApiHooksBotcentralRouteImport } from './routes/api/hooks/botcentral'
import { Route as ApiHooksDeployedRouteImport } from './routes/api/hooks/deployed'
import { Route as ApiHooksGithubRouteImport } from './routes/api/hooks/github'
import { Route as ApiOauthGithubRouteImport } from './routes/api/oauth/github'
import { Route as ApiOauthGithubCallbackRouteImport } from './routes/api/oauth/github-callback'
import { Route as ApiOauthGoogleRouteImport } from './routes/api/oauth/google'
import { Route as ApiOauthGoogleCallbackRouteImport } from './routes/api/oauth/google-callback'
import { Route as ApiOauthProvidersRouteImport } from './routes/api/oauth/providers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const TopupRoute = TopupRouteImport.update({
  id: '/topup',
  path: '/topup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiForgotRoute = ApiForgotRouteImport.update({
  id: '/api/forgot',
  path: '/api/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoginRoute = ApiLoginRouteImport.update({
  id: '/api/login',
  path: '/api/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogoutRoute = ApiLogoutRouteImport.update({
  id: '/api/logout',
  path: '/api/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResetRoute = ApiResetRouteImport.update({
  id: '/api/reset',
  path: '/api/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignupRoute = ApiSignupRouteImport.update({
  id: '/api/signup',
  path: '/api/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnGlossaryRoute = LearnGlossaryRouteImport.update({
  id: '/learn/glossary',
  path: '/learn/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnQuizRoute = LearnQuizRouteImport.update({
  id: '/learn/quiz',
  path: '/learn/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesIdRoute = SitesIdRouteImport.update({
  id: '/sites/$id',
  path: '/sites/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHooksBotcentralRoute = ApiHooksBotcentralRouteImport.update({
  id: '/api/hooks/botcentral',
  path: '/api/hooks/botcentral',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHooksDeployedRoute = ApiHooksDeployedRouteImport.update({
  id: '/api/hooks/deployed',
  path: '/api/hooks/deployed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHooksGithubRoute = ApiHooksGithubRouteImport.update({
  id: '/api/hooks/github',
  path: '/api/hooks/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthGithubRoute = ApiOauthGithubRouteImport.update({
  id: '/api/oauth/github',
  path: '/api/oauth/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthGithubCallbackRoute = ApiOauthGithubCallbackRouteImport.update({
  id: '/api/oauth/github-callback',
  path: '/api/oauth/github-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthGoogleRoute = ApiOauthGoogleRouteImport.update({
  id: '/api/oauth/google',
  path: '/api/oauth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthGoogleCallbackRoute = ApiOauthGoogleCallbackRouteImport.update({
  id: '/api/oauth/google-callback',
  path: '/api/oauth/google-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthProvidersRoute = ApiOauthProvidersRouteImport.update({
  id: '/api/oauth/providers',
  path: '/api/oauth/providers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/fleet': typeof FleetRoute
  '/health': typeof HealthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRoute
  '/playbook': typeof PlaybookRoute
  '/reset': typeof ResetRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/topup': typeof TopupRoute
  '/api/forgot': typeof ApiForgotRoute
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/me': typeof ApiMeRoute
  '/api/reset': typeof ApiResetRoute
  '/api/signup': typeof ApiSignupRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/learn/glossary': typeof LearnGlossaryRoute
  '/learn/quiz': typeof LearnQuizRoute
  '/sites/$id': typeof SitesIdRoute
  '/learn/': typeof LearnIndexRoute
  '/api/hooks/botcentral': typeof ApiHooksBotcentralRoute
  '/api/hooks/deployed': typeof ApiHooksDeployedRoute
  '/api/hooks/github': typeof ApiHooksGithubRoute
  '/api/oauth/github': typeof ApiOauthGithubRoute
  '/api/oauth/github-callback': typeof ApiOauthGithubCallbackRoute
  '/api/oauth/google': typeof ApiOauthGoogleRoute
  '/api/oauth/google-callback': typeof ApiOauthGoogleCallbackRoute
  '/api/oauth/providers': typeof ApiOauthProvidersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/fleet': typeof FleetRoute
  '/health': typeof HealthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRoute
  '/playbook': typeof PlaybookRoute
  '/reset': typeof ResetRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/topup': typeof TopupRoute
  '/api/forgot': typeof ApiForgotRoute
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/me': typeof ApiMeRoute
  '/api/reset': typeof ApiResetRoute
  '/api/signup': typeof ApiSignupRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/learn/glossary': typeof LearnGlossaryRoute
  '/learn/quiz': typeof LearnQuizRoute
  '/sites/$id': typeof SitesIdRoute
  '/learn': typeof LearnIndexRoute
  '/api/hooks/botcentral': typeof ApiHooksBotcentralRoute
  '/api/hooks/deployed': typeof ApiHooksDeployedRoute
  '/api/hooks/github': typeof ApiHooksGithubRoute
  '/api/oauth/github': typeof ApiOauthGithubRoute
  '/api/oauth/github-callback': typeof ApiOauthGithubCallbackRoute
  '/api/oauth/google': typeof ApiOauthGoogleRoute
  '/api/oauth/google-callback': typeof ApiOauthGoogleCallbackRoute
  '/api/oauth/providers': typeof ApiOauthProvidersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/fleet': typeof FleetRoute
  '/health': typeof HealthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRoute
  '/playbook': typeof PlaybookRoute
  '/reset': typeof ResetRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/topup': typeof TopupRoute
  '/api/forgot': typeof ApiForgotRoute
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/me': typeof ApiMeRoute
  '/api/reset': typeof ApiResetRoute
  '/api/signup': typeof ApiSignupRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/learn/glossary': typeof LearnGlossaryRoute
  '/learn/quiz': typeof LearnQuizRoute
  '/sites/$id': typeof SitesIdRoute
  '/learn/': typeof LearnIndexRoute
  '/api/hooks/botcentral': typeof ApiHooksBotcentralRoute
  '/api/hooks/deployed': typeof ApiHooksDeployedRoute
  '/api/hooks/github': typeof ApiHooksGithubRoute
  '/api/oauth/github': typeof ApiOauthGithubRoute
  '/api/oauth/github-callback': typeof ApiOauthGithubCallbackRoute
  '/api/oauth/google': typeof ApiOauthGoogleRoute
  '/api/oauth/google-callback': typeof ApiOauthGoogleCallbackRoute
  '/api/oauth/providers': typeof ApiOauthProvidersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/fleet'
    | '/health'
    | '/llms.txt'
    | '/login'
    | '/ops'
    | '/playbook'
    | '/reset'
    | '/sitemap.xml'
    | '/start'
    | '/topup'
    | '/api/forgot'
    | '/api/login'
    | '/api/logout'
    | '/api/me'
    | '/api/reset'
    | '/api/signup'
    | '/learn/$slug'
    | '/learn/glossary'
    | '/learn/quiz'
    | '/sites/$id'
    | '/learn/'
    | '/api/hooks/botcentral'
    | '/api/hooks/deployed'
    | '/api/hooks/github'
    | '/api/oauth/github'
    | '/api/oauth/github-callback'
    | '/api/oauth/google'
    | '/api/oauth/google-callback'
    | '/api/oauth/providers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/fleet'
    | '/health'
    | '/llms.txt'
    | '/login'
    | '/ops'
    | '/playbook'
    | '/reset'
    | '/sitemap.xml'
    | '/start'
    | '/topup'
    | '/api/forgot'
    | '/api/login'
    | '/api/logout'
    | '/api/me'
    | '/api/reset'
    | '/api/signup'
    | '/learn/$slug'
    | '/learn/glossary'
    | '/learn/quiz'
    | '/sites/$id'
    | '/learn'
    | '/api/hooks/botcentral'
    | '/api/hooks/deployed'
    | '/api/hooks/github'
    | '/api/oauth/github'
    | '/api/oauth/github-callback'
    | '/api/oauth/google'
    | '/api/oauth/google-callback'
    | '/api/oauth/providers'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/fleet'
    | '/health'
    | '/llms.txt'
    | '/login'
    | '/ops'
    | '/playbook'
    | '/reset'
    | '/sitemap.xml'
    | '/start'
    | '/topup'
    | '/api/forgot'
    | '/api/login'
    | '/api/logout'
    | '/api/me'
    | '/api/reset'
    | '/api/signup'
    | '/learn/$slug'
    | '/learn/glossary'
    | '/learn/quiz'
    | '/sites/$id'
    | '/learn/'
    | '/api/hooks/botcentral'
    | '/api/hooks/deployed'
    | '/api/hooks/github'
    | '/api/oauth/github'
    | '/api/oauth/github-callback'
    | '/api/oauth/google'
    | '/api/oauth/google-callback'
    | '/api/oauth/providers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  FleetRoute: typeof FleetRoute
  HealthRoute: typeof HealthRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LoginRoute: typeof LoginRoute
  OpsRoute: typeof OpsRoute
  PlaybookRoute: typeof PlaybookRoute
  ResetRoute: typeof ResetRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StartRoute: typeof StartRoute
  TopupRoute: typeof TopupRoute
  ApiForgotRoute: typeof ApiForgotRoute
  ApiLoginRoute: typeof ApiLoginRoute
  ApiLogoutRoute: typeof ApiLogoutRoute
  ApiMeRoute: typeof ApiMeRoute
  ApiResetRoute: typeof ApiResetRoute
  ApiSignupRoute: typeof ApiSignupRoute
  LearnSlugRoute: typeof LearnSlugRoute
  LearnGlossaryRoute: typeof LearnGlossaryRoute
  LearnQuizRoute: typeof LearnQuizRoute
  SitesIdRoute: typeof SitesIdRoute
  LearnIndexRoute: typeof LearnIndexRoute
  ApiHooksBotcentralRoute: typeof ApiHooksBotcentralRoute
  ApiHooksDeployedRoute: typeof ApiHooksDeployedRoute
  ApiHooksGithubRoute: typeof ApiHooksGithubRoute
  ApiOauthGithubRoute: typeof ApiOauthGithubRoute
  ApiOauthGithubCallbackRoute: typeof ApiOauthGithubCallbackRoute
  ApiOauthGoogleRoute: typeof ApiOauthGoogleRoute
  ApiOauthGoogleCallbackRoute: typeof ApiOauthGoogleCallbackRoute
  ApiOauthProvidersRoute: typeof ApiOauthProvidersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topup': {
      id: '/topup'
      path: '/topup'
      fullPath: '/topup'
      preLoaderRoute: typeof TopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forgot': {
      id: '/api/forgot'
      path: '/api/forgot'
      fullPath: '/api/forgot'
      preLoaderRoute: typeof ApiForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/login': {
      id: '/api/login'
      path: '/api/login'
      fullPath: '/api/login'
      preLoaderRoute: typeof ApiLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logout': {
      id: '/api/logout'
      path: '/api/logout'
      fullPath: '/api/logout'
      preLoaderRoute: typeof ApiLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reset': {
      id: '/api/reset'
      path: '/api/reset'
      fullPath: '/api/reset'
      preLoaderRoute: typeof ApiResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signup': {
      id: '/api/signup'
      path: '/api/signup'
      fullPath: '/api/signup'
      preLoaderRoute: typeof ApiSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/glossary': {
      id: '/learn/glossary'
      path: '/learn/glossary'
      fullPath: '/learn/glossary'
      preLoaderRoute: typeof LearnGlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/quiz': {
      id: '/learn/quiz'
      path: '/learn/quiz'
      fullPath: '/learn/quiz'
      preLoaderRoute: typeof LearnQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$id': {
      id: '/sites/$id'
      path: '/sites/$id'
      fullPath: '/sites/$id'
      preLoaderRoute: typeof SitesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hooks/botcentral': {
      id: '/api/hooks/botcentral'
      path: '/api/hooks/botcentral'
      fullPath: '/api/hooks/botcentral'
      preLoaderRoute: typeof ApiHooksBotcentralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hooks/deployed': {
      id: '/api/hooks/deployed'
      path: '/api/hooks/deployed'
      fullPath: '/api/hooks/deployed'
      preLoaderRoute: typeof ApiHooksDeployedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hooks/github': {
      id: '/api/hooks/github'
      path: '/api/hooks/github'
      fullPath: '/api/hooks/github'
      preLoaderRoute: typeof ApiHooksGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/github': {
      id: '/api/oauth/github'
      path: '/api/oauth/github'
      fullPath: '/api/oauth/github'
      preLoaderRoute: typeof ApiOauthGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/github-callback': {
      id: '/api/oauth/github-callback'
      path: '/api/oauth/github-callback'
      fullPath: '/api/oauth/github-callback'
      preLoaderRoute: typeof ApiOauthGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/google': {
      id: '/api/oauth/google'
      path: '/api/oauth/google'
      fullPath: '/api/oauth/google'
      preLoaderRoute: typeof ApiOauthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/google-callback': {
      id: '/api/oauth/google-callback'
      path: '/api/oauth/google-callback'
      fullPath: '/api/oauth/google-callback'
      preLoaderRoute: typeof ApiOauthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/providers': {
      id: '/api/oauth/providers'
      path: '/api/oauth/providers'
      fullPath: '/api/oauth/providers'
      preLoaderRoute: typeof ApiOauthProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  FleetRoute: FleetRoute,
  HealthRoute: HealthRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LoginRoute: LoginRoute,
  OpsRoute: OpsRoute,
  PlaybookRoute: PlaybookRoute,
  ResetRoute: ResetRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StartRoute: StartRoute,
  TopupRoute: TopupRoute,
  ApiForgotRoute: ApiForgotRoute,
  ApiLoginRoute: ApiLoginRoute,
  ApiLogoutRoute: ApiLogoutRoute,
  ApiMeRoute: ApiMeRoute,
  ApiResetRoute: ApiResetRoute,
  ApiSignupRoute: ApiSignupRoute,
  LearnSlugRoute: LearnSlugRoute,
  LearnGlossaryRoute: LearnGlossaryRoute,
  LearnQuizRoute: LearnQuizRoute,
  SitesIdRoute: SitesIdRoute,
  LearnIndexRoute: LearnIndexRoute,
  ApiHooksBotcentralRoute: ApiHooksBotcentralRoute,
  ApiHooksDeployedRoute: ApiHooksDeployedRoute,
  ApiHooksGithubRoute: ApiHooksGithubRoute,
  ApiOauthGithubRoute: ApiOauthGithubRoute,
  ApiOauthGithubCallbackRoute: ApiOauthGithubCallbackRoute,
  ApiOauthGoogleRoute: ApiOauthGoogleRoute,
  ApiOauthGoogleCallbackRoute: ApiOauthGoogleCallbackRoute,
  ApiOauthProvidersRoute: ApiOauthProvidersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
