/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LearnIndexRouteImport } from './routes/learn/index'
import { Route as LearnSlugRouteImport } from './routes/learn/$slug'
import { Route as LearnGlossaryRouteImport } from './routes/learn/glossary'
import { Route as LearnQuizRouteImport } from './routes/learn/quiz'
import { Route as SitesIdRouteImport } from './routes/sites/$id'
import { Route as ApiHooksDeployedRouteImport } from './routes/api/hooks/deployed'
import { Route as ApiHooksGithubRouteImport } from './routes/api/hooks/github'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnGlossaryRoute = LearnGlossaryRouteImport.update({
  id: '/learn/glossary',
  path: '/learn/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnQuizRoute = LearnQuizRouteImport.update({
  id: '/learn/quiz',
  path: '/learn/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesIdRoute = SitesIdRouteImport.update({
  id: '/sites/$id',
  path: '/sites/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHooksDeployedRoute = ApiHooksDeployedRouteImport.update({
  id: '/api/hooks/deployed',
  path: '/api/hooks/deployed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHooksGithubRoute = ApiHooksGithubRouteImport.update({
  id: '/api/hooks/github',
  path: '/api/hooks/github',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/fleet': typeof FleetRoute
  '/health': typeof HealthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/ops': typeof OpsRoute
  '/playbook': typeof PlaybookRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/learn/glossary': typeof LearnGlossaryRoute
  '/learn/quiz': typeof LearnQuizRoute
  '/sites/$id': typeof SitesIdRoute
  '/learn/': typeof LearnIndexRoute
  '/api/hooks/deployed': typeof ApiHooksDeployedRoute
  '/api/hooks/github': typeof ApiHooksGithubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/fleet': typeof FleetRoute
  '/health': typeof HealthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/ops': typeof OpsRoute
  '/playbook': typeof PlaybookRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/learn/glossary': typeof LearnGlossaryRoute
  '/learn/quiz': typeof LearnQuizRoute
  '/sites/$id': typeof SitesIdRoute
  '/learn': typeof LearnIndexRoute
  '/api/hooks/deployed': typeof ApiHooksDeployedRoute
  '/api/hooks/github': typeof ApiHooksGithubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/fleet': typeof FleetRoute
  '/health': typeof HealthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/ops': typeof OpsRoute
  '/playbook': typeof PlaybookRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/learn/glossary': typeof LearnGlossaryRoute
  '/learn/quiz': typeof LearnQuizRoute
  '/sites/$id': typeof SitesIdRoute
  '/learn/': typeof LearnIndexRoute
  '/api/hooks/deployed': typeof ApiHooksDeployedRoute
  '/api/hooks/github': typeof ApiHooksGithubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/fleet'
    | '/health'
    | '/llms.txt'
    | '/ops'
    | '/playbook'
    | '/sitemap.xml'
    | '/learn/$slug'
    | '/learn/glossary'
    | '/learn/quiz'
    | '/sites/$id'
    | '/learn/'
    | '/api/hooks/deployed'
    | '/api/hooks/github'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/fleet'
    | '/health'
    | '/llms.txt'
    | '/ops'
    | '/playbook'
    | '/sitemap.xml'
    | '/learn/$slug'
    | '/learn/glossary'
    | '/learn/quiz'
    | '/sites/$id'
    | '/learn'
    | '/api/hooks/deployed'
    | '/api/hooks/github'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/fleet'
    | '/health'
    | '/llms.txt'
    | '/ops'
    | '/playbook'
    | '/sitemap.xml'
    | '/learn/$slug'
    | '/learn/glossary'
    | '/learn/quiz'
    | '/sites/$id'
    | '/learn/'
    | '/api/hooks/deployed'
    | '/api/hooks/github'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  FleetRoute: typeof FleetRoute
  HealthRoute: typeof HealthRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  OpsRoute: typeof OpsRoute
  PlaybookRoute: typeof PlaybookRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LearnSlugRoute: typeof LearnSlugRoute
  LearnGlossaryRoute: typeof LearnGlossaryRoute
  LearnQuizRoute: typeof LearnQuizRoute
  SitesIdRoute: typeof SitesIdRoute
  LearnIndexRoute: typeof LearnIndexRoute
  ApiHooksDeployedRoute: typeof ApiHooksDeployedRoute
  ApiHooksGithubRoute: typeof ApiHooksGithubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/glossary': {
      id: '/learn/glossary'
      path: '/learn/glossary'
      fullPath: '/learn/glossary'
      preLoaderRoute: typeof LearnGlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/quiz': {
      id: '/learn/quiz'
      path: '/learn/quiz'
      fullPath: '/learn/quiz'
      preLoaderRoute: typeof LearnQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$id': {
      id: '/sites/$id'
      path: '/sites/$id'
      fullPath: '/sites/$id'
      preLoaderRoute: typeof SitesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hooks/deployed': {
      id: '/api/hooks/deployed'
      path: '/api/hooks/deployed'
      fullPath: '/api/hooks/deployed'
      preLoaderRoute: typeof ApiHooksDeployedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hooks/github': {
      id: '/api/hooks/github'
      path: '/api/hooks/github'
      fullPath: '/api/hooks/github'
      preLoaderRoute: typeof ApiHooksGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  FleetRoute: FleetRoute,
  HealthRoute: HealthRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  OpsRoute: OpsRoute,
  PlaybookRoute: PlaybookRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LearnSlugRoute: LearnSlugRoute,
  LearnGlossaryRoute: LearnGlossaryRoute,
  LearnQuizRoute: LearnQuizRoute,
  SitesIdRoute: SitesIdRoute,
  LearnIndexRoute: LearnIndexRoute,
  ApiHooksDeployedRoute: ApiHooksDeployedRoute,
  ApiHooksGithubRoute: ApiHooksGithubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
