import type { Bot } from "./types";

export const FLEET_TEMPLATE: Omit<Bot, "currentTaskId" | "currentSiteId" | "lastHeartbeat">[] =
  [
    {
      id: "bot-aether",
      name: "Aether",
      callsign: "AETHER",
      role: "Technical SEO / crawl integrity",
      specialty: "SPA fallback, HTTP status, deep-link fetchability",
      playbookIds: ["spa_fallback"],
      engines: ["google", "bing", "gemini", "chatgpt"],
      status: "idle",
    },
    {
      id: "bot-helios",
      name: "Helios",
      callsign: "HELIOS",
      role: "Google & Gemini door",
      specialty: "Search Console, sitemaps, URL Inspection",
      playbookIds: ["sitemap", "gsc_submit"],
      engines: ["google", "gemini", "meta-ai"],
      status: "idle",
    },
    {
      id: "bot-nimbus",
      name: "Nimbus",
      callsign: "NIMBUS",
      role: "Bing & IndexNow door",
      specialty: "Webmaster Tools, IndexNow pings, ChatGPT/Copilot feed",
      playbookIds: ["bing_webmaster", "indexnow"],
      engines: ["bing", "indexnow", "chatgpt", "copilot", "perplexity"],
      status: "idle",
    },
    {
      id: "bot-orion",
      name: "Orion",
      callsign: "ORION",
      role: "Crawler access control",
      specialty: "robots.txt allowlists for AI answer engines",
      playbookIds: ["robots_ai", "botcentral_list"],
      engines: ["chatgpt", "perplexity", "claude", "google", "bing"],
      status: "idle",
    },
    {
      id: "bot-lyra",
      name: "Lyra",
      callsign: "LYRA",
      role: "Grok / X mention agent",
      specialty: "Live X posts that Grok actually searches",
      playbookIds: ["x_mentions"],
      engines: ["grok"],
      status: "idle",
    },
    {
      id: "bot-vesper",
      name: "Vesper",
      callsign: "VESPER",
      role: "Directory & review listings",
      specialty: "Product Hunt, AlternativeTo, SaaSHub, Trustpilot",
      playbookIds: ["directories"],
      engines: ["chatgpt", "perplexity", "claude", "gemini"],
      status: "idle",
    },
    {
      id: "bot-cassian",
      name: "Cassian",
      callsign: "CASSIAN",
      role: "Press & authority citations",
      specialty: "Vertical press pitches and referring domains",
      playbookIds: ["press"],
      engines: ["chatgpt", "claude", "gemini", "perplexity", "grok"],
      status: "idle",
    },
    {
      id: "bot-forge",
      name: "Forge",
      callsign: "FORGE",
      role: "Product foundation",
      specialty: "Public-page health, schema, trust features",
      playbookIds: ["app_health"],
      engines: ["google", "gemini"],
      status: "idle",
    },
    {
      id: "bot-sentinel",
      name: "Sentinel",
      callsign: "SENTINEL",
      role: "Monitor & recrawl",
      specialty: "Evidence loop across GSC, Bing, HTTP, mentions",
      playbookIds: ["monitor"],
      engines: ["google", "bing", "grok", "chatgpt"],
      status: "idle",
    },
  ];
